### ISSUE TITLE
Most pages are broken

### ISSUE THREAD

**Issue by markbrough** [IATI/IATI-Dashboard#447] opened 2017-10-18 06:29 UTC
See http://dashboard.iatistandard.org/

index.html is missing, as are many other pages, and even pages that do exist appear to be broken (I guess png/json files are missing or something)

![grafik](https://user-images.githubusercontent.com/688113/31703754-df3f3578-b3ff-11e7-8eca-9ed6777e3122.png)

**Comment by siemvaessen** [comment] 2017-10-18 07:07
Probably relates to this - https://discuss.iatistandard.org/t/back-to-the-essense/1062/8?u=siemvaessen

@dalepotter?

**Comment by hayfield** [comment] 2017-10-18 07:47
Am looking into it now

**Comment by hayfield** [comment] 2017-10-18 08:02
There are now pages on the Dashboard (there may be the odd thing missing, though it looks OK from a quick look). Am investigating the cause of the problem.

**Comment by hayfield** [comment] 2017-10-18 08:27
My assessment (I've not been directly involved in any of the steps, so @dalepotter would have to confirm) is:

* Something happened to cause the problem @siemvaessen linked to
* A temporary fix was applied to solve this on Friday
* The temporary fix interfered with the daily generation process, so the Dashboard didn't re-generate over the weekend
* A permanent fix to this (yesterday) interfered with the multi-stage generation process in an unexpected manner
* It *should* work fine for the next generation

**Comment by andylolz** [comment] 2017-12-03 22:06
I don’t suppose it’s related… But the dashboard is currently down.

**Comment by dalepotter** [comment] 2017-12-04 10:12
Thanks @andylolz - our automated tests started failing for the Dashboard on Saturday night around 9:20pm. I'm looking at getting it back online now...

**Comment by dalepotter** [comment] 2017-12-04 14:10
The Dashboard is now back on line again - apologies for the outage. After it has successfully generated again tonight I will close this issue.

**Comment by andylolz** [comment] 2017-12-04 14:17
Thanks for sorting it, @dalepotter!

What caused the outage over the weekend?

**Comment by andylolz** [comment] 2018-04-13 10:28
> After it has successfully generated again tonight I will close this issue.

It has been a few months, so I guess this can be closed now.

**Closed** 2019-01-17 15:30 UTC
