### ISSUE TITLE
Adjust Calculation Of Spend Ratio To Use Paired Data As Priority

### ISSUE THREAD

**Issue by iatisupport** [IATI/IATI-Dashboard#396] opened 2016-04-07 08:34 UTC
Currently Spend Ratio is based on whichever is the greatest result from the following calculations:

2014 IATI Spend / 2014 Reference Spend
2015 IATI Spend / 2015 Reference Spend
2015 IATI Spend / 2014 Reference Spend
2015 IATI Spend / 2015 Official Forecast

However, experience has demonstrated that the calculation

2015 IATI Spend / 2014 Reference Spend

should only be done when none of the other matching pairs of data are available. This is because:

a) if a complete pair of data (eg 2014 IATI Spend & 2014 Reference Spend)  is available then it makes sense that the results of that calculation is used as the actual Spend ratio score
b) Use of 2015 IATI Spend / 2014 Reference Spend can benefit publishers who are currently publishing cumulative rather than annualised transactions

**Comment by dalepotter** [comment] 2016-04-07 08:42
This issue is a duplicate of https://github.com/IATI/IATI-Dashboard/issues/375#issuecomment-199299075

Will therefore close this issue.

**Closed by dalepotter** 2016-04-07 08:42 UTC
