### ISSUE TITLE
Joining stats when publishers change reporting org

### ISSUE THREAD

**Issue by bill-anderson** [IATI/IATI-Dashboard#358] opened 2015-11-12 21:54 UTC
EU/EC publishers are being unfairly penalised for changing reporting-org id

**Comment by dalepotter** [comment] 2015-11-30 15:38
This appears to be a duplicate of https://github.com/IATI/IATI-Dashboard/issues/353

**Comment by dalepotter** [comment] 2015-11-30 16:07
This issue appears to impact upon the timeliness page, do post if there are any other pages where publishers are being unfairly penalised?

**Closed** 2017-03-16 16:38 UTC
Labels: indicator
